export const attributeWeighting = [
  {
    positions: ['GK'],
    weighting: [0, 0, 0, 0, 0, 0, 1],
  },
  {
    positions: ['CB'],
    weighting: [0.05, 0, 0.64, 0.09, 0.02, 0.2, 0],
  },
  {
    positions: ['LWB', 'RWB', 'LB', 'RB'],
    weighting: [0.19, 0, 0.44, 0.17, 0.1, 0.1, 0],
  },
  {
    positions: ['CDM'],
    weighting: [0.28, 0, 0.4, 0.17, 0, 0.15, 0],
  },
  {
    positions: ['CM', 'LM', 'RM'],
    weighting: [0.43, 0.12, 0.1, 0.29, 0, 0.06, 0],
  },
  {
    positions: ['CAM'],
    weighting: [0.34, 0.21, 0, 0.38, 0.07, 0, 0],
  },
  {
    positions: ['CF', 'LW', 'RW'],
    weighting: [0.24, 0.23, 0, 0.4, 0.13, 0, 0],
  },
  {
    positions: ['ST'],
    weighting: [0.1, 0.46, 0, 0.29, 0.1, 0.05, 0],
  },
];

export const positionalFamiliarity = [
  {
    primaryPosition: 'GK',
    adjustment: {
      GK: 0,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'CB',
    adjustment: {
      GK: -20,
      CB: 0,
      RB: -8,
      LB: -8,
      RWB: -20,
      LWB: -20,
      CDM: -8,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'RB',
    adjustment: {
      GK: -20,
      CB: -8,
      RB: 0,
      LB: -8,
      RWB: -5,
      LWB: -20,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -8,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'LB',
    adjustment: {
      GK: -20,
      CB: -8,
      RB: -8,
      LB: 0,
      RWB: -20,
      LWB: -5,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -8,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'RWB',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -5,
      LB: -20,
      RWB: 0,
      LWB: -8,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -8,
      LM: -20,
      RW: -8,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'LWB',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -5,
      RWB: -8,
      LWB: 0,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -8,
      RW: -20,
      LW: -8,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'CDM',
    adjustment: {
      GK: -20,
      CB: -8,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: 0,
      CM: -5,
      CAM: -8,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'CM',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: -5,
      CM: 0,
      CAM: -5,
      RM: -8,
      LM: -8,
      RW: -20,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'CAM',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: -8,
      CM: -5,
      CAM: 0,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -5,
      ST: -20,
    },
  },
  {
    primaryPosition: 'RM',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -8,
      LB: -20,
      RWB: -8,
      LWB: -20,
      CDM: -20,
      CM: -8,
      CAM: -20,
      RM: 0,
      LM: -8,
      RW: -5,
      LW: -20,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'LM',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -8,
      RWB: -20,
      LWB: -8,
      CDM: -20,
      CM: -8,
      CAM: -20,
      RM: -8,
      LM: 0,
      RW: -20,
      LW: -5,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'RW',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -8,
      LWB: -20,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -5,
      LM: -20,
      RW: 0,
      LW: -8,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'LW',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -8,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -5,
      RW: -8,
      LW: 0,
      CF: -20,
      ST: -20,
    },
  },
  {
    primaryPosition: 'CF',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: -20,
      CM: -20,
      CAM: -5,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: 0,
      ST: -5,
    },
  },
  {
    primaryPosition: 'ST',
    adjustment: {
      GK: -20,
      CB: -20,
      RB: -20,
      LB: -20,
      RWB: -20,
      LWB: -20,
      CDM: -20,
      CM: -20,
      CAM: -20,
      RM: -20,
      LM: -20,
      RW: -20,
      LW: -20,
      CF: -5,
      ST: 0,
    },
  },
];

export const captainBoost = [
  {
    positions: ['GK'],
    adjustment: {
      defense: 2,
      physical: 0,
      passing: 0,
      dribbling: 0,
      shooting: 0,
      pace: 0,
      goalkeeping: 0,
    },
  },
  {
    positions: ['CB', 'LWB', 'RWB', 'LB', 'RB'],
    adjustment: {
      defense: 2,
      physical: 1,
      passing: 0,
      dribbling: 0,
      shooting: 0,
      pace: 0,
      goalkeeping: 0,
    },
  },
  {
    positions: ['CDM', 'CM', 'LM', 'RM', 'CAM'],
    adjustment: {
      defense: 0,
      physical: 0,
      passing: 2,
      dribbling: 1,
      shooting: 0,
      pace: 0,
      goalkeeping: 0,
    },
  },
  {
    positions: ['CF', 'LW', 'RW', 'ST'],
    adjustment: {
      defense: 0,
      physical: 0,
      passing: 0,
      dribbling: 0,
      shooting: 2,
      pace: 1,
      goalkeeping: 0,
    },
  },
];
